language: node_js
node_js:
- '8'
- '6'
cache: yarn
env:
  global:
    secure: XEu++JnrdmcpmpNlNOv6hi8SOJyue/fxEwOk3XholYTqvc4pAIcrVgc1d1LYBt5aHeUqJKz6ddpVFN12KG7zR16bQNQTcpdjhlEv97evXDKi1fUMglcODqJJE64E3wpOguaSteJSSErfP3kf6WhERaOM4B/rMvZ0vZ1enwsOZghsWCq14I17qIYUC3h0fSmpH0nSpAoYTVU1giqo4AUZ+YQR7XLQvrJjYcncZuAeT9BJsuveFYFqgGw03aHVXNqAlIIhV4S5PK7Hwa7S9lBdSvkQKRQqYOm6Kq/nzhhSmvBHsXrdQ03lThfb3wtwF0P/kkIPXTL82v/ggcWWkTjB3k+Ak+e+AEiXtJPhbKmMNnc4XminhnCitQUUvR7U5lk8lJFAnzOleoFGhu//t60hdrTABOmfiSuHo5NPDMpHjb8SlYx4dmXfbJmcJDJtkW/UknfHikF37BQA8wc5ywm+mdpSmNG47ZzPMvKqvc2VWuMbUJGrSutB41TfgfAD3fI66x0U/eg9Uv1ImquO6g4C+zfqJvGoEul/SSLuWvBpyDObOwoaawcfyH5ka1+xsxlpGdCisJTCu4ilhQ0emr2Sdg43SLIQsTO+EqDcyUsF4W1Gfjj+1lWCeOlkjqSeoQoxSHBLLaH+zwtKRkl/AU9FQJ0eKOnBmTNghkLcedhgX4w=
before_install: yarn global add greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
script:
- npm run ci
after_script: greenkeeper-lockfile-upload
deploy:
  provider: npm
  skip_cleanup: true
  email: marcus.mennemeier@actano.de
  api_key:
    secure: QKcDUYRriwsAwmc9lFFW+ixFPEnPHYh98v5REOL422XrY9lMx02ObaU8oYOhFJIPVW9Kzju9I8IF7WlphWdD0SbXzQISKMoxt2IYZv/5H32hur+qAW0dpyV0per/RbyBnCQFOWE22IC0taUYjAvLUyHUFI6fI5sfhGjwe4pDCLa9m3vqlTt8dm2cMFl4dcEDwYOfg5neVSoe/1DORGBf/DTf9B2nY5fyprHk9Y7CZbp8HM/giEemgiefXEHAR2nu4L2HxFubHAUwn4Q0YA0z2VeNdnSE/20jU1jaQy/BF0gLi7Ruylx7t7FsCh8RCNGV+z8MCkjWkwqzKBYMsFJjBcBRr1KFmTYSZ1YuTVfS/zRHRMXesxsmgIyRUJxSjvEtTSuDvoOPgH2NL8sCx+/tGiKBATChCpSEtnA/l8nTRQTLLrNXzTM+7YZokk5L//Fd+Vyvbz8bazIc9uww1ntn6iItdr3+FoT4a69nKAn617rLLEre3abNVv+zJTQ+Zgl6v1lSwcFUkH072mwn+aB3z1vvprHjonPcCiW6T/XpOeeabnAZ3UJGFwDWPtS9uiaaAV4JsV0CvqOI2cX1v7s6tDuPBd6aiHpwx1sM8woC47/R9w8R6sV0BxXNqcXiYYI/LvjDaedWBXiyQsAug8lOe353AH9h2exNTjXYCwpXcVQ=
  on:
    tags: true
    repo: actano/borders-smtp-client
    node: '8'
